# Generated by Django 5.0.7 on 2026-08-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationrequest",
            name="requested_password",
        ),
    ]
